"""Generate appapi OpenAPI JSON for frontend type tooling."""

import json
import os
import sys
from typing import Any
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ.setdefault("MARKET_LOG_DIR", ".tmp/openapi-logs")

from appapi.main import app


def _schema_ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _literal(value: Any) -> str:
    return json.dumps(value)


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _schema_ref_name(schema["$ref"])

    if "anyOf" in schema:
        return " | ".join(_ts_type(item) for item in schema["anyOf"])

    if "enum" in schema:
        return " | ".join(_literal(item) for item in schema["enum"])

    schema_type = schema.get("type")
    if schema_type == "array":
        item_type = _ts_type(schema.get("items", {}))
        if " | " in item_type:
            return f"({item_type})[]"
        return f"{item_type}[]"
    if schema_type == "object":
        value_schema = schema.get("additionalProperties")
        if isinstance(value_schema, dict):
            return f"Record<string, {_ts_type(value_schema)}>"
        return "Record<string, unknown>"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "string":
        return "string"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    return "unknown"


def _ts_interface(name: str, schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in properties.items():
        optional = "" if property_name in required else "?"
        lines.append(f"  {property_name}{optional}: {_ts_type(property_schema)};")
    lines.append("}")
    return "\n".join(lines)


def _generate_types(openapi: dict[str, Any]) -> str:
    schemas = openapi["components"]["schemas"]
    parts = [
        "// Generated from appapi OpenAPI schemas by scripts/generate_openapi.py.",
        "// Do not edit this file by hand.",
        "",
    ]
    for name in sorted(schemas):
        schema = schemas[name]
        if schema.get("type") == "object":
            parts.append(_ts_interface(name, schema))
            parts.append("")
    parts.extend(
        [
            "export type BacktestResult = BacktestRunResponse;",
            "export type BacktestRunParams = BacktestRunRequest;",
        ],
    )
    parts.append("")
    return "\n".join(parts)


def main() -> int:
    openapi = app.openapi()
    output_dir = Path("appui/src/api/generated")
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "openapi.json").write_text(
        json.dumps(openapi, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    (output_dir / "types.ts").write_text(_generate_types(openapi), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
